name: Update .luacheckrc

on:
  push:
    paths:
      - '.luacheckrc_header'
      - '.github/workflows/main.yml'
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate new .luacheckrc
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Rulesets
    - name: Clone FG-Unofficial-Developers-Guild/CoreRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/CoreRPG
        path: .fg/rulesets/CoreRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/2E
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/2E
        path: .fg/rulesets/DND2E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/3.5E
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/3.5E
        path: .fg/rulesets/DND35E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/4e
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/4e
        path: .fg/rulesets/DND4E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/5e
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/5e
        path: .fg/rulesets/DND5E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/PFRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/PFRPG
        path: .fg/rulesets/PFRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/PFRPG2
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/PFRPG2
        path: .fg/rulesets/PFRPG2
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/SFRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/SFRPG
        path: .fg/rulesets/SFRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    # bmos extensions
    - name: Clone bmos/FG-PFRPG-Encumbrance-Penalties
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-PFRPG-Encumbrance-Penalties
        path: .fg/extensions/FG-PFRPG-Encumbrance-Penalties
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-PFRPG-Advanced-Crit-and-Fumble-Tables
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-PFRPG-Advanced-Crit-and-Fumble-Tables
        path: .fg/extensions/FG-PFRPG-Advanced-Crit-and-Fumble-Tables
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-PFRPG-Advanced-Effects
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/FG-PFRPG-Advanced-Effects
        path: .fg/extensions/FG-PFRPG-Advanced-Effects
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-PFRPG-Drain-and-Permanent-Bonuses
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-PFRPG-Drain-and-Permanent-Bonuses
        path: .fg/extensions/FG-PFRPG-Drain-and-Permanent-Bonuses
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-FG-CoreRPG-Extraplanar-Containers
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-CoreRPG-Extraplanar-Containers
        path: .fg/extensions/FG-CoreRPG-Extraplanar-Containers
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-CoreRPG-Coins-Weight
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-CoreRPG-Coins-Weight
        path: .fg/extensions/FG-CoreRPG-Coins-Weight
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-Ammunition-Manager
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-Ammunition-Manager
        path: .fg/extensions/FG-Ammunition-Manager
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-PFRPG-Upgrade-NPC-Actions
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-PFRPG-Upgrade-NPC-Actions
        path: .fg/extensions/FG-PFRPG-Upgrade-NPC-Actions
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-PFRPG-Spell-Formatting
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-PFRPG-Spell-Formatting
        path: .fg/extensions/FG-PFRPG-Spell-Formatting
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-PFRPG-Spell-Failure
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-PFRPG-Spell-Failure
        path: .fg/extensions/FG-PFRPG-Spell-Failure
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-PFRPG-Sanity-Tracker
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-PFRPG-Sanity-Tracker
        path: .fg/extensions/FG-PFRPG-Sanity-Tracker
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-PFRPG-Malady-Tracker
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-PFRPG-Malady-Tracker
        path: .fg/extensions/FG-PFRPG-Malady-Tracker
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-HitMargins
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-HitMargins
        path: .fg/extensions/FG-HitMargins
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-PFRPG-Live-Hitpoints
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-PFRPG-Live-Hitpoints
        path: .fg/extensions/FG-PFRPG-Live-Hitpoints
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-PFRPG-Item-Durability
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-PFRPG-Item-Durability
        path: .fg/extensions/FG-PFRPG-Item-Durability
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone bmos/FG-PFRPG-Extra-Stat-to-Saves
      uses: actions/checkout@v3
      with:
        repository: bmos/FG-PFRPG-Extra-Stat-to-Saves
        path: .fg/extensions/FG-PFRPG-Extra-Stat-to-Saves
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-PFRPG-ExtendedACBonusTypes
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/FG-PFRPG-ExtendedACBonusTypes
        path: .fg/extensions/FG-PFRPG-ExtendedACBonusTypes
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-PFRPG-Enhanced-Items
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/FG-PFRPG-Enhanced-Items
        path: .fg/extensions/FG-PFRPG-Enhanced-Items
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-PFRPG-Customized-Item-Generator
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/FG-PFRPG-Customized-Item-Generator
        path: .fg/extensions/FG-PFRPG-Customized-Item-Generator
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-PFRPG-Advanced-Item-Actions
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/FG-PFRPG-Advanced-Item-Actions
        path: .fg/extensions/FG-PFRPG-Advanced-Item-Actions
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-CoreRPG-Party-Inventory-Weight
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/FG-CoreRPG-Party-Inventory-Weight
        path: .fg/extensions/FG-CoreRPG-Party-Inventory-Weight
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-CoreRPG-Party-Inventory-Identified
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/FG-CoreRPG-Party-Inventory-Identified
        path: .fg/extensions/FG-CoreRPG-Party-Inventory-Identified
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-CoreRPG-Moon-Tracker
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/FG-CoreRPG-Moon-Tracker
        path: .fg/extensions/FG-CoreRPG-Moon-Tracker
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-Aura-Effect
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/FG-Aura-Effect
        path: .fg/extensions/FG-Aura-Effect
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-4E-TEMPO-and-TEMPA
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/FG-4E-TEMPO-and-TEMPA
        path: .fg/extensions/FG-4E-TEMPO-and-TEMPA
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    # Other dev's extensions
    - name: Clone Kelrugem/Extended-automation-and-overlays
      uses: actions/checkout@v3
      with:
        repository: Kelrugem/Extended-automation-and-overlays
        path: .fg/extensions/Extended-automation-and-overlays
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-ClockAdjuster
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/FG-ClockAdjuster
        path: .fg/extensions/FG-ClockAdjuster
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/BetterCombatEffects
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/BetterCombatEffects
        path: .fg/extensions/BetterCombatEffects
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone MeAndUnique/SizeMatters
      uses: actions/checkout@v3
      with:
        repository: MeAndUnique/SizeMatters
        path: .fg/extensions/SizeMatters
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone MeAndUnique/TemporalFixation
      uses: actions/checkout@v3
      with:
        repository: MeAndUnique/TemporalFixation
        path: .fg/extensions/TemporalFixation
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone SirMotte/FGU-Theme-Hearth
      uses: actions/checkout@v3
      with:
        repository: SirMotte/FGU-Theme-Hearth
        path: .fg/extensions/FGU-Theme-Hearth
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/Turbo
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/Turbo
        path: .fg/extensions/Turbo
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/Contaminated
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/Contaminated
        path: .fg/extensions/Contaminated
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/FranklyNot
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/FranklyNot
        path: .fg/extensions/FranklyNot
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/PowerUp
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/PowerUp
        path: .fg/extensions/PowerUp
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/Exhausted
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/Exhausted
        path: .fg/extensions/Exhausted
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/ChatAestheticsConfigurator
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/ChatAestheticsConfigurator
        path: .fg/extensions/ChatAestheticsConfigurator
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/ArcaneWard
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/ArcaneWard
        path: .fg/extensions/ArcaneWard
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/EffectiveInitiative
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/EffectiveInitiative
        path: .fg/extensions/EffectiveInitiative
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/HighVariance
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/HighVariance
        path: .fg/extensions/HighVariance
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/Effective-NPC
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/Effective-NPC
        path: .fg/extensions/Effective-NPC
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone rhagelstrom/BetterCombatEffectsGold
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/BetterCombatEffectsGold
        path: .fg/extensions/BetterCombatEffectsGold
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    # Processing
    - name: Generate new .luacheckrc
      uses: FG-Unofficial-Developers-Guild/action-generate-luacheckrc@main
      with:
        std: '+dnd2e+dnd35e+dnd4e+dnd5e+pfrpg+pfrpg2'

    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        title: Update .luacheckrc
        commit-message: "test: update .luacheckrc"
        branch: update-luacheckrc
        delete-branch: true
