name: Update .luacheckrc

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    paths:
      - '.luacheckrc_header'

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate new .luacheckrc
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Rulesets
    - name: Clone FG-Unofficial-Developers-Guild/CoreRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/CoreRPG
        path: .fg/rulesets/CoreRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/2E
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/2E
        path: .fg/rulesets/DND2E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/3.5E
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/3.5E
        path: .fg/rulesets/DND35E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/4e
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/4e
        path: .fg/rulesets/DND4E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/5e
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/5e
        path: .fg/rulesets/DND5E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/PFRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/PFRPG
        path: .fg/rulesets/PFRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/PFRPG2
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/PFRPG2
        path: .fg/rulesets/PFRPG2
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/SFRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/SFRPG
        path: .fg/rulesets/SFRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    # Extensions
    - name: Clone rhagelstrom/Exhausted
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/Exhausted
        path: .fg/extensions/Exhausted
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone rhagelstrom/BetterCombatEffects
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/BetterCombatEffects
        path: .fg/extensions/BetterCombatEffects
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    # Processing 
    - name: Generate new .luacheckrc
      uses: FG-Unofficial-Developers-Guild/action-generate-luacheckrc@621bf7039348197209c647e3c8eb6c2e895f08f7
      with:
        std: '+dnd2e+dnd35e+dnd4e+dnd5e+pfrpg+pfrpg2'

    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        title: Update .luacheckrc
        commit-message: "test: update .luacheckrc"
        branch: update-luacheckrc
        delete-branch: true
